x-portainer-volumes: &portainer-volumes
  - /etc/localtime:/etc/localtime:ro
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - ./portainer-data:/data

version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:2.15.1-alpine
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes: *portainer-volumes
    ports:
      - 9000:9000